### ISSUE TITLE
Crusher crashes with hopper

### ISSUE THREAD

**Issue by medsal15** [MinestrapTeam/Minestrappolation-4#36]
It was crushing a gold ore, I placed a hopper under it for automation and then:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  CCCDeobfPlugin (unknown)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.34-universal.jar)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.82-universal.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 02.06.15 15:51
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at net.minecraft.tileentity.TileEntityHopper.func_174917_b(TileEntityHopper.java:352)
    at net.minecraft.tileentity.TileEntityHopper.func_145891_a(TileEntityHopper.java:384)
    at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:215)
    at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:195)
    at net.minecraft.world.World.func_72939_s(World.java:1735)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:703)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.tileentity.TileEntityHopper.func_174917_b(TileEntityHopper.java:352)
    at net.minecraft.tileentity.TileEntityHopper.func_145891_a(TileEntityHopper.java:384)
    at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:215)
    at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:195)

-- Block entity being ticked --
Details:
    Name: Hopper // net.minecraft.tileentity.TileEntityHopper
    Block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-451,3,95), Chunk: (at 13,0,15 in -29,5; contains blocks -464,0,80 to -449,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1735)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)

-- Affected level --
Details:
    Level name: tests
    All players: 1 total; [EntityPlayerMP['medsal15'/8, l='tests', x=-452.14, y=4.00, z=95.82]]
    Chunk stats: ServerChunkCache: 731 Drop: 0
    Level seed: 3280887401970901756
    Level generator: ID 01 - flat, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: -613.00,4.00,54.00 - World: (-613,4,54), Chunk: (at 11,0,6 in -39,3; contains blocks -624,0,48 to -609,255,63), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
    Level time: 7232 game time, 7232 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 146876 (now: false), thunder time: 82102 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:703)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 79341520 bytes (75 MB) / 457117696 bytes (435 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.10 FML v8.99.18.1419 Minecraft Forge 11.14.1.1419 7 mods loaded, 7 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{8.99.18.1419} [Forge Mod Loader](forge-1.8-11.14.1.1419.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{11.14.1.1419} [Minecraft Forge](forge-1.8-11.14.1.1419.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.5.34} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.5.82} [Not Enough Items](NotEnoughItems-1.8-1.0.5.82-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ministrapp{1.8.0-4.0.0A} [Minestrappolation](Minestrappolation-1.8-4.0.0.nightly_19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.6.0_B1} [Waila](Waila-1.6.0_B1_1.8.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CCCDeobfPlugin (unknown)

CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.34-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
NEICorePlugin (NotEnoughItems-1.8-1.0.5.82-universal.jar)
  codechicken.nei.asm.NEITransformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['medsal15'/8, l='tests', x=-452.14, y=4.00, z=95.82]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by werty1124** [comment]
Same as #35
