### ISSUE TITLE
Crash: Need help!

### ISSUE THREAD

**Issue by Plaxius** [MinestrapTeam/Minestrappolation-4#93]
I'm currently using Magic Launcher to test the mod's compatibility with the game.  I'm using Forge 1.8-11.14.3.1450.  When I run the test, everything runs smoothly for a while, but then the log spits out this error:

Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraftforge.fluids.Fluid.<init>(Ljava/lang/String;Lnet/minecraft/util/ResourceLocation;Lnet/minecraft/util/ResourceLocation;)V
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:553)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:248)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:412)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at magic.launcher.Launcher.main(SourceFile:214)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.fluids.Fluid.<init>(Ljava/lang/String;Lnet/minecraft/util/ResourceLocation;Lnet/minecraft/util/ResourceLocation;)V
    at minestrapteam.mods.minestrappolation.lib.MFluid.init(MFluid.java:25)
    at minestrapteam.mods.minestrappolation.Minestrappolation.preInit(Minestrappolation.java:71)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:537)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:550)
    ... 15 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 319174352 bytes (304 MB) / 496500736 bytes (473 MB) up to 496500736 bytes (473 MB)
    JVM Flags: 3 total; -Xms512m -Xmx512m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1450 4 mods loaded, 4 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCH    FML{8.0.99.99} [Forge Mod Loader](forge-1.8-11.14.3.1450.jar) 
    UCH    Forge{11.14.3.1450} [Minecraft Forge](forge-1.8-11.14.3.1450.jar) 
    UCE    ministrapp{1.8.0-4.1.0} [Minestrappolation Mod](Minestrappolation-1.8-4.0.0.nightly_257.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.3.12804 Compatibility Profile Context 13.352.1004.1008' Renderer: 'AMD Radeon(TM) R5 Graphics'
[20:11:08] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:571]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users******\AppData\Roaming.minecraft\crash-reports\crash-2015-08-28_20.11.08-client.txt
2015-08-28 20:11:08,642 ERROR Attempted to append to non-started appender FmlSysOut

Do you have any idea what could cause this error?  Thanks in advance!

**Comment by Delocuro** [comment]
Update Forge. You need 11.14.3.1500 or higher.
